package kr.co.donghyun.pinglauncher.presentation.util.dns

import android.content.Context
import android.net.ConnectivityManager
import android.util.Log
import java.io.File

/**
 * Android 의 ConnectivityManager 에서 활성 네트워크의 DNS 서버를 읽어
 * /etc/resolv.conf 포맷으로 파일에 쓰고, libpojavexec.so 의 bytehook 으로
 * JDK 가 /etc/resolv.conf 를 읽으려 할 때 우리 파일을 대신 읽게 한다.
 *
 * 결과: MC 의 SRV 레코드 조회 (JNDI DNS 경유) 가 동작 → kr 서버 SRV 도메인 접속 가능.
 */
object DnsHookNative {
    private const val TAG = "DnsHookNative"
    private val FALLBACK = listOf("8.8.8.8", "1.1.1.1", "8.8.4.4")

    init {
        // 호출 시점에 libpojavexec 가 이미 로드돼 있어야 함.
        // MinecraftActivity.setupAndLaunch() 에서 이미 로드한 다음에 호출.
    }

    @JvmStatic external fun installResolvConfRedirect(path: String)

    fun setup(context: Context) {
        val servers = queryAndroidDnsServers(context)
            .ifEmpty { FALLBACK }
            .also { Log.d(TAG, "사용할 DNS 서버: $it") }

        val resolvConf = File(context.cacheDir, "resolv.conf")
        resolvConf.writeText(buildString {
            append("# auto-generated by PingLauncher\n")
            servers.forEach { append("nameserver ").append(it).append('\n') }
        })
        Log.d(TAG, "resolv.conf 작성: ${resolvConf.absolutePath}")

        try {
            installResolvConfRedirect(resolvConf.absolutePath)
        } catch (e: UnsatisfiedLinkError) {
            Log.e(TAG, "installResolvConfRedirect 바인딩 실패 — libpojavexec.so 미로드?", e)
        }
    }

    private fun queryAndroidDnsServers(context: Context): List<String> {
        return try {
            val cm = context.getSystemService(Context.CONNECTIVITY_SERVICE) as ConnectivityManager
            val network = cm.activeNetwork ?: return emptyList()
            val lp = cm.getLinkProperties(network) ?: return emptyList()
            lp.dnsServers.mapNotNull { addr ->
                addr.hostAddress?.takeIf {
                    // IPv6 link-local 등 NDP 사용 불가 주소 제거
                    !it.startsWith("fe80:") && !it.contains("%")
                }
            }
        } catch (e: Exception) {
            Log.w(TAG, "Android DNS 조회 실패: ${e.message}")
            emptyList()
        }
    }
}