package kr.co.donghyun.pinglauncher.presentation.util.hosts

import android.content.Context
import android.util.Log
import com.google.gson.Gson
import com.google.gson.reflect.TypeToken
import java.io.File

/**
 * 사용자가 추가한 호스트네임 ↔ IP 매핑을 관리한다.
 *
 * 용도:
 *  - Hamachi: 25.x.x.x IP 를 친구가 알려준 닉네임으로 매핑 (단말이 Hamachi 네트워크에
 *    실제로 연결돼 있어야 라우팅됨 — Hamachi 모바일 앱 / VPN 필요)
 *  - LAN: 친구 PC 의 사설 IP 를 알아보기 쉬운 이름으로
 *  - 차단 우회: 특정 도메인을 다른 IP 로 강제
 *
 * 형식: 표준 /etc/hosts 포맷
 *   "<ip>  <hostname>  [<alias> ...]"
 */
data class HostEntry(
    val hostname: String,
    val ip: String,
    val note: String = "",      // 사용자 메모용 (UI 표시만)
    val enabled: Boolean = true,
)

object HostsManager {
    private const val TAG = "HostsManager"
    private const val PREFS_FILE = "custom_hosts.json"
    private val gson = Gson()

    fun load(context: Context): List<HostEntry> = try {
        val f = File(context.filesDir, PREFS_FILE)
        if (!f.exists()) emptyList()
        else gson.fromJson<List<HostEntry>>(
            f.readText(),
            object : TypeToken<List<HostEntry>>() {}.type
        ) ?: emptyList()
    } catch (e: Exception) {
        Log.w(TAG, "load 실패: ${e.message}")
        emptyList()
    }

    fun save(context: Context, entries: List<HostEntry>) {
        try {
            File(context.filesDir, PREFS_FILE).writeText(gson.toJson(entries))
        } catch (e: Exception) {
            Log.e(TAG, "save 실패: ${e.message}", e)
        }
    }

    /**
     * 호출 시점에 항상 새로 빌드. 부팅 직전(DnsHookNative.setup) 에 한 번 부른다.
     * 기본 entry (localhost) + 사용자 entry 를 합쳐서 cache/hosts 로 떨어뜨림.
     */
    fun buildHostsFile(context: Context): File {
        val hostsFile = File(context.cacheDir, "hosts")
        val sb = StringBuilder()
        sb.appendLine("# auto-generated by PingLauncher")
        sb.appendLine("127.0.0.1\tlocalhost")
        sb.appendLine("::1\t\tlocalhost")

        val entries = load(context).filter { it.enabled }
        if (entries.isNotEmpty()) {
            sb.appendLine("")
            sb.appendLine("# user-defined")
            entries.forEach { e ->
                if (isValidIp(e.ip) && isValidHostname(e.hostname)) {
                    sb.append(e.ip).append('\t').append(e.hostname)
                    if (e.note.isNotBlank()) {
                        sb.append("  # ").append(e.note.replace('\n', ' '))
                    }
                    sb.append('\n')
                } else {
                    Log.w(TAG, "잘못된 entry 무시: ${e.hostname} → ${e.ip}")
                }
            }
        }
        hostsFile.writeText(sb.toString())
        return hostsFile
    }

    private fun isValidIp(s: String): Boolean {
        // IPv4 만 허용 (Minecraft 서버 IP 는 거의 다 IPv4)
        val parts = s.split('.')
        if (parts.size != 4) return false
        return parts.all { p ->
            val n = p.toIntOrNull() ?: return false
            n in 0..255
        }
    }

    private fun isValidHostname(s: String): Boolean {
        if (s.isBlank() || s.length > 253) return false
        return s.all { c ->
            c.isLetterOrDigit() || c == '.' || c == '-' || c == '_'
        }
    }
}